# Db connection test
GET http://localhost:5000/test-db

# Register a new user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "fullname": "Gideon Ngetich",
  "email": "gideon.ngetich@outlook.com",
  "password": "password123"
}

###

# Register another user (admin)
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "fullname": "Admin User",
  "email": "admin@example.com",
  "password": "admin123",
  "role": "admin"
}

###

# Login with user credentials
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "gideon.ngetich@outlook.com",
  "password": "password123"
}

###

# Login with admin credentials
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}

###

# Get all users (requires authentication)
GET http://localhost:5000/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJfaWQiOjIsImZ1bGxuYW1lIjoiQWRtaW4gVXNlciIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NTUxMTYxNDQsImlhdCI6MTc1NTAyOTc0NH0.GVjavyUiDdVI31arXekq1EzreGk7mtDcqEKh0vyL_Wc

###

# Get user by ID
GET http://localhost:5000/auth/users/1
# Authorization: Bearer your_jwt_token_here

###

# Update user
PUT http://localhost:5000/auth/users/1
# Authorization: Bearer your_jwt_token_here
Content-Type: application/json

{
  "fullname": "Ngetich Updated",
  "email": "gideon.ngetich@outlook.com"
}

###

### Task Management Tests ###
